version: "1.0"
info:
  model: int-scaffold
packages:
- name: LDS1_GITProject
  gitServerName: remoteGit
  gitUrl: https://github.com/Hariharan-SV-IBM
  gitUsername: Hariharan-SV-IBM
  gitBranch: main
